# Generated by Django 5.1.2 on 2025-09-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='Room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='User_name',
            new_name='sender',
        ),
    ]
